# Generated by Django 2.0.8 on 2018-09-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readcsv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='status',
            field=models.IntegerField(default=-1),
        ),
    ]
